"""
Arbitrage Strategy Module
Strategy 1: Auto-trade mispriced markets

Primary signal: Quantitative log-normal model driven by live OHLCV data (ATR-based vol).
Secondary signal: AI confirms or adjusts the quant estimate (optional, 30% weight).

For non-crypto markets the AI is still used as the primary estimator (no quant signal).
If AI is unavailable AND the market is not a crypto price market, the market is skipped.
"""

import logging
import math
import re
from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass
from datetime import datetime, timezone

from ..market.scanner import Market
from ..analysis.ai_agent import AIAnalysis, AIAgent
from ..analysis.math_utils import PositionSizer, calculate_arbitrage_profit

logger = logging.getLogger(__name__)


@dataclass
class TradeSignal:
    """Trading signal generated by strategy"""

    market_id: str
    token_id_yes: str
    token_id_no: str
    market_question: str
    end_date: Optional[datetime]
    action: str  # "BUY_YES", "BUY_NO"
    price: float
    size: float
    edge: float
    ai_confidence: float
    reasoning: str
    timestamp: datetime
    auto_execute: bool = True


# ---------------------------------------------------------------------------
# Quantitative probability engine
# ---------------------------------------------------------------------------

class CryptoPriceAnalyzer:
    """
    Log-normal probability estimator for crypto price prediction markets.

    Model (no-drift, martingale approximation):
        P(S_T > K) = 1 - Φ( ln(K / S₀) / (σ_daily × √T) )
        P(S_T < K) = Φ( ln(K / S₀) / (σ_daily × √T) )

    Volatility is derived from the 15-minute ATR supplied by BTCPriceService:
        σ_daily = ATR_15m × √96 / current_price
    (96 fifteen-minute bars per trading day)
    """

    # Map question keywords → canonical asset ticker
    _ASSET_MAP: Dict[str, str] = {
        "bitcoin": "BTC",
        "btc": "BTC",
        "ethereum": "ETH",
        "eth": "ETH",
        "solana": "SOL",
        "sol": "SOL",
    }

    # Direction keywords
    _ABOVE_WORDS = frozenset({"above", "over", "exceed", "exceeds", "reach", "reaches", "hit", "hits", "surpass", "surpasses"})
    _BELOW_WORDS = frozenset({"below", "under", "drop", "drops", "fall", "falls", "dip", "dips"})

    # Sanity bounds per asset (min, max in USD)
    _PRICE_BOUNDS: Dict[str, Tuple[float, float]] = {
        "BTC": (1_000, 10_000_000),
        "ETH": (50, 500_000),
        "SOL": (0.5, 50_000),
    }

    @staticmethod
    def _norm_cdf(x: float) -> float:
        """Standard normal CDF via math.erf (no scipy dependency)."""
        return 0.5 * (1.0 + math.erf(x / math.sqrt(2.0)))

    # ------------------------------------------------------------------
    # Market detection
    # ------------------------------------------------------------------

    def detect_crypto_market(self, question: str) -> Optional[Dict[str, Any]]:
        """
        Parse a market question for a crypto price threshold.

        Returns:
            {'asset': 'BTC'/'ETH'/'SOL', 'target': float, 'direction': 'above'/'below'}
            or None if the question is not a crypto price market.
        """
        q = question.lower()

        # 1. Identify asset
        asset: Optional[str] = None
        for keyword, ticker in self._ASSET_MAP.items():
            if keyword in q:
                asset = ticker
                break
        if asset is None:
            return None

        # 2. Extract price target  ($70,000  |  $70k  |  70000  |  70k)
        target = self._extract_price(q)
        if target is None:
            return None

        # 3. Sanity-check magnitude
        lo, hi = self._PRICE_BOUNDS.get(asset, (1, 10_000_000))
        if not (lo <= target <= hi):
            return None

        # 4. Determine direction (default: above)
        direction = "above"
        for word in self._BELOW_WORDS:
            if word in q:
                direction = "below"
                break

        return {"asset": asset, "target": target, "direction": direction}

    @staticmethod
    def _extract_price(text: str) -> Optional[float]:
        """
        Extract the first dollar-style price from lowercased text.

        Handles: $70,000  $70k  $100K  70000  70k
        Returns the numeric value in USD, or None.
        """
        # Priority 1: explicit $ sign with optional k-multiplier
        m = re.search(r"\$([\d,]+(?:\.\d+)?)\s*([kK])\b", text)
        if m:
            try:
                return float(m.group(1).replace(",", "")) * 1_000
            except ValueError:
                pass

        m = re.search(r"\$([\d,]+(?:\.\d+)?)\b", text)
        if m:
            try:
                return float(m.group(1).replace(",", ""))
            except ValueError:
                pass

        # Priority 2: bare large number (≥4 digits) possibly with k
        m = re.search(r"\b([\d,]{4,})\s*([kK])\b", text)
        if m:
            try:
                return float(m.group(1).replace(",", "")) * 1_000
            except ValueError:
                pass

        m = re.search(r"\b([\d,]{4,}(?:\.\d+)?)\b", text)
        if m:
            try:
                return float(m.group(1).replace(",", ""))
            except ValueError:
                pass

        return None

    # ------------------------------------------------------------------
    # Probability model
    # ------------------------------------------------------------------

    def estimate_probability(
        self,
        current_price: float,
        target_price: float,
        direction: str,
        days_to_expiry: float,
        atr_15m: float,
    ) -> Optional[float]:
        """
        Compute market-implied probability using the log-normal no-drift model.

        Args:
            current_price:  Live spot price in USD.
            target_price:   Threshold from the market question.
            direction:      'above' or 'below'.
            days_to_expiry: Calendar days until market resolution.
            atr_15m:        Current 15-minute ATR in USD (from BTCPriceService).

        Returns:
            Probability in (0.01, 0.99) or None if inputs are invalid.
        """
        if any(v <= 0 for v in (current_price, target_price, days_to_expiry, atr_15m)):
            return None

        # Convert 15m ATR → daily volatility (fractional)
        # σ_daily ≈ ATR_15m × √96 / S₀
        daily_vol = (atr_15m * math.sqrt(96)) / current_price
        # Clamp to plausible range: 0.5% – 20% per day
        daily_vol = max(0.005, min(0.20, daily_vol))

        log_return = math.log(target_price / current_price)
        sigma_sqrt_t = daily_vol * math.sqrt(days_to_expiry)

        if sigma_sqrt_t < 1e-9:
            # Essentially at expiry
            if direction == "above":
                return 0.99 if current_price >= target_price else 0.01
            else:
                return 0.99 if current_price <= target_price else 0.01

        z = log_return / sigma_sqrt_t

        if direction == "above":
            prob = 1.0 - self._norm_cdf(z)
        else:
            prob = self._norm_cdf(z)

        return max(0.01, min(0.99, prob))

    @staticmethod
    def confidence_from_edge(edge: float) -> float:
        """Map raw edge → confidence score for position sizing."""
        if edge >= 0.25:
            return 0.90
        if edge >= 0.18:
            return 0.82
        if edge >= 0.12:
            return 0.74
        return 0.66


# ---------------------------------------------------------------------------
# Main strategy class
# ---------------------------------------------------------------------------

class ArbitrageStrategy:
    """
    Strategy 1: Auto-trade Mispriced Markets

    Routing logic per market:
    ┌────────────────────────┬────────────┬─────────────────────────────────┐
    │ Market type            │ quant avail│ Action                          │
    ├────────────────────────┼────────────┼─────────────────────────────────┤
    │ Crypto price threshold │ Yes        │ Quant (70%) + optional AI (30%) │
    │ Any market             │ No         │ AI-only (if AI online)          │
    │ Any market             │ No         │ Skip (AI offline)               │
    └────────────────────────┴────────────┴─────────────────────────────────┘
    """

    def __init__(
        self,
        config: Dict[str, Any],
        ai_agent: AIAgent,
        position_sizer: PositionSizer,
        btc_service=None,   # Optional[BTCPriceService]
    ):
        self.config = config.get("strategies", {}).get("arbitrage", {})
        self.ai_agent = ai_agent
        self.position_sizer = position_sizer
        self.btc_service = btc_service          # shared instance from BitcoinStrategy

        # Configuration
        self.enabled = self.config.get("enabled", False)
        self.use_ai = self.config.get("use_ai", False)
        self.min_edge = self.config.get("min_edge", 0.10)
        self.ai_confidence_threshold = self.config.get("ai_confidence_threshold", 0.70)
        self.fee_buffer = self.config.get("fee_buffer", 0.02)
        self.safety_margin = self.config.get("safety_margin", 0.03)

        # Entry price range for AI-only signals (sweet spot from backtests)
        self.ai_entry_price_min = self.config.get("entry_price_min", 0.20)
        self.ai_entry_price_max = self.config.get("entry_price_max", 0.40)

        # Entry price range for quant signals (much wider — model is calibrated)
        self.quant_entry_price_min = self.config.get("quant_entry_price_min", 0.10)
        self.quant_entry_price_max = self.config.get("quant_entry_price_max", 0.90)

        # Convergence arbitrage threshold (community standard: 0.96).
        # When YES + NO sum ≤ this value the spread is a guaranteed profit at
        # resolution regardless of outcome. Bypasses probability edge requirements.
        # Set to 0.0 to disable the convergence path entirely.
        self.convergence_arb_threshold = self.config.get("convergence_arb_threshold", 0.96)

        # Quant engine
        self._quant = CryptoPriceAnalyzer()

        # State
        self.last_analysis: Dict[str, AIAnalysis] = {}
        self.processed_markets: set = set()
        self._max_processed = 5000
        self._max_analysis_cache = 500

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    async def scan_and_analyze(
        self, markets: List[Market], bankroll: float
    ) -> List[TradeSignal]:
        """
        Scan markets and generate trade signals.

        For crypto price markets: quant model primary, AI optional confirmer.
        For all other markets: AI primary (skipped if AI offline).
        """
        if not self.enabled:
            return []

        signals = []

        # Fetch live BTC data once for the whole batch (avoids N redundant calls)
        btc_analysis = None
        if self.btc_service is not None:
            try:
                btc_analysis = await self.btc_service.get_full_analysis()
            except Exception as exc:
                logger.warning(f"ArbitrageStrategy: could not fetch BTC analysis: {exc}")

        for market in markets:
            if market.id in self.processed_markets:
                continue

            if not market.is_binary:
                continue

            if market.spread > self.config.get("max_spread", 0.05):
                logger.debug(f"Skipping {market.question[:50]} — spread {market.spread:.3f}")
                continue

            # Route to the appropriate analyser
            crypto_info = self._quant.detect_crypto_market(market.question)

            if crypto_info and btc_analysis:
                # ── Quantitative path ──────────────────────────────────────
                signal = await self._analyze_crypto_quant(
                    market=market,
                    crypto_info=crypto_info,
                    btc_analysis=btc_analysis,
                    bankroll=bankroll,
                )
            else:
                # ── AI-only path ───────────────────────────────────────────
                if not self.use_ai:
                    continue
                # Gate: only call AI for markets in the sweet-spot price range
                if not (
                    self.ai_entry_price_min <= market.yes_price <= self.ai_entry_price_max
                    or self.ai_entry_price_min <= market.no_price <= self.ai_entry_price_max
                ):
                    continue  # price outside range — no edge, skip without AI call

                signal = await self._analyze_ai_only(market=market, bankroll=bankroll)

            if signal:
                signals.append(signal)
                self.processed_markets.add(market.id)

        # Evict oldest entries when processed_markets grows too large
        if len(self.processed_markets) > self._max_processed:
            oldest = list(self.processed_markets)[
                : len(self.processed_markets) - self._max_processed
            ]
            for k in oldest:
                self.processed_markets.discard(k)

        return signals

    # ------------------------------------------------------------------
    # Quant analysis path
    # ------------------------------------------------------------------

    async def _analyze_crypto_quant(
        self,
        market: Market,
        crypto_info: Dict[str, Any],
        btc_analysis,
        bankroll: float,
    ) -> Optional[TradeSignal]:
        """
        Generate a signal using the log-normal model.

        AI is called if available and provides a 30% blend on the probability.
        """
        asset = crypto_info["asset"]
        target = crypto_info["target"]
        direction = crypto_info["direction"]

        # Resolve live price and ATR for the asset
        current_price = btc_analysis.current_price
        atr_15m = getattr(btc_analysis.trend_sabre, "atr", None)

        if current_price is None or current_price <= 0:
            logger.debug(f"Quant: no current price for {asset}, skipping {market.id}")
            return None

        if atr_15m is None or atr_15m <= 0:
            # Fall back to a rough estimate: ~1.5% of price per 15m bar
            atr_15m = current_price * 0.015
            logger.debug(f"Quant: ATR unavailable for {asset}, using fallback {atr_15m:.2f}")

        # Days to expiry
        days = self._days_to_expiry(market)
        if days < 0.01:
            return None  # expired

        # Primary quant probability
        quant_prob = self._quant.estimate_probability(
            current_price=current_price,
            target_price=target,
            direction=direction,
            days_to_expiry=days,
            atr_15m=atr_15m,
        )
        if quant_prob is None:
            return None

        # Optional AI blend (30%)
        ai_prob: Optional[float] = None
        ai_reasoning = ""
        if self.use_ai:
            try:
                ai_analysis = await self.ai_agent.analyze_market(
                    market_question=market.question,
                    market_description=market.description,
                    current_yes_price=market.yes_price,
                    market_id=market.id,
                )
                if ai_analysis and ai_analysis.recommendation != "HOLD":
                    ai_prob = ai_analysis.estimated_probability
                    ai_reasoning = ai_analysis.reasoning
                    self._cache_analysis(market.id, ai_analysis)
            except Exception as exc:
                logger.debug(f"Quant path: AI call failed ({exc}); proceeding with quant only")

        # Blend: 70% quant + 30% AI (if available)
        if ai_prob is not None:
            blended_prob = 0.70 * quant_prob + 0.30 * ai_prob
            reasoning = (
                f"[QUANT+AI] BTC=${current_price:,.0f} | target=${target:,.0f} "
                f"| {direction} in {days:.1f}d | ATR={atr_15m:.2f} "
                f"| quant={quant_prob:.3f} ai={ai_prob:.3f} blend={blended_prob:.3f} | {ai_reasoning}"
            )
        else:
            blended_prob = quant_prob
            reasoning = (
                f"[QUANT] BTC=${current_price:,.0f} | target=${target:,.0f} "
                f"| {direction} in {days:.1f}d | ATR={atr_15m:.2f} "
                f"| quant_prob={quant_prob:.3f}"
            )

        # ── Convergence arbitrage check ───────────────────────────────────────
        # When YES+NO sum is below the threshold (default 0.96), the spread
        # is a guaranteed profit at resolution regardless of outcome.
        # This path bypasses probability-edge requirements — the profit is
        # structural (market mispricing), not directional.
        # TODO: Future enhancement — generate dual-leg signals (BUY_YES + BUY_NO)
        #       to lock in profit on both sides simultaneously. For now we enter
        #       the better-probability side to benefit from the spread.
        pair_cost = market.yes_price + market.no_price
        if (
            self.convergence_arb_threshold > 0
            and pair_cost <= self.convergence_arb_threshold
        ):
            conv_edge = 1.0 - pair_cost  # guaranteed spread
            # Take the side with higher probability, or YES if equal
            if blended_prob >= 0.5:
                action = "BUY_YES"
                price = market.yes_price
            else:
                action = "BUY_NO"
                price = market.no_price
            edge = conv_edge
            logger.info(
                f"CONVERGENCE ARB: {market.question[:60]} | "
                f"YES={market.yes_price:.3f} NO={market.no_price:.3f} "
                f"sum={pair_cost:.3f} spread={conv_edge:.3f} -> {action}"
            )
        else:
            # ── Standard probability-edge path ────────────────────────────────
            yes_edge = blended_prob - market.yes_price
            no_edge = (1.0 - blended_prob) - market.no_price

            effective_yes = yes_edge - self.fee_buffer - self.safety_margin
            effective_no  = no_edge  - self.fee_buffer - self.safety_margin

            if effective_yes >= self.min_edge and effective_yes >= effective_no:
                action = "BUY_YES"
                price = market.yes_price
                edge = yes_edge
            elif effective_no >= self.min_edge:
                action = "BUY_NO"
                price = market.no_price
                edge = no_edge
            else:
                logger.debug(
                    f"Quant: insufficient edge for {market.question[:50]} "
                    f"(yes_edge={yes_edge:.3f}, no_edge={no_edge:.3f})"
                )
                return None

        # Relaxed entry price filter for quant signals
        if not (self.quant_entry_price_min <= price <= self.quant_entry_price_max):
            return None

        confidence = self._quant.confidence_from_edge(edge)
        auto_execute = edge >= 0.15  # stronger threshold for auto-execute

        win_prob = blended_prob if action == "BUY_YES" else (1.0 - blended_prob)
        position = self.position_sizer.calculate_position_size(
            bankroll=bankroll,
            win_probability=win_prob,
            current_price=price,
            ai_estimated_prob=win_prob,
        )
        if position.amount < self.position_sizer.min_position:
            return None

        logger.info(
            f"Quant signal: {action} {market.question[:60]} | "
            f"price={price:.3f} edge={edge:.3f} prob={blended_prob:.3f} size=${position.amount:.2f}"
        )

        return TradeSignal(
            market_id=market.id,
            token_id_yes=market.token_id_yes,
            token_id_no=market.token_id_no,
            market_question=market.question,
            end_date=market.end_date,
            action=action,
            price=price,
            size=position.amount,
            edge=edge,
            ai_confidence=confidence,
            reasoning=reasoning,
            timestamp=datetime.now(),
            auto_execute=auto_execute,
        )

    # ------------------------------------------------------------------
    # AI-only analysis path  (non-crypto markets)
    # ------------------------------------------------------------------

    async def _analyze_ai_only(
        self, market: Market, bankroll: float
    ) -> Optional[TradeSignal]:
        """
        Generate a signal using the AI agent only.
        Returns None immediately if AI is unavailable.
        """
        try:
            analysis = await self.ai_agent.analyze_market(
                market_question=market.question,
                market_description=market.description,
                current_yes_price=market.yes_price,
                market_id=market.id,
            )
        except Exception as exc:
            logger.debug(f"AI-only path: error for {market.id}: {exc}")
            return None

        if not analysis:
            return None

        self._cache_analysis(market.id, analysis)

        if analysis.recommendation == "HOLD":
            logger.debug(f"AI recommends HOLD for {market.question[:50]} — skipping")
            self.processed_markets.add(market.id)
            return None

        return self._generate_signal_from_ai(market=market, analysis=analysis, bankroll=bankroll)

    # ------------------------------------------------------------------
    # Signal generation from AI analysis (AI-only path)
    # ------------------------------------------------------------------

    def _generate_signal_from_ai(
        self, market: Market, analysis: AIAnalysis, bankroll: float
    ) -> Optional[TradeSignal]:
        """Build a TradeSignal from an AI analysis result."""

        yes_edge = analysis.estimated_probability - market.yes_price
        no_edge  = (1 - analysis.estimated_probability) - market.no_price

        effective_yes = yes_edge - self.fee_buffer - self.safety_margin
        effective_no  = no_edge  - self.fee_buffer - self.safety_margin

        action = price = edge = None

        if effective_yes > self.min_edge and analysis.recommendation == "BUY_YES":
            action, price, edge = "BUY_YES", market.yes_price, yes_edge
        elif effective_no > self.min_edge and analysis.recommendation == "BUY_NO":
            action, price, edge = "BUY_NO", market.no_price, no_edge

        if not action:
            return None

        # AI sweet-spot price filter
        if price < self.ai_entry_price_min or price > self.ai_entry_price_max:
            return None

        auto_execute = analysis.confidence_score >= self.ai_confidence_threshold

        win_prob = (
            analysis.estimated_probability
            if action == "BUY_YES"
            else (1 - analysis.estimated_probability)
        )

        position = self.position_sizer.calculate_position_size(
            bankroll=bankroll,
            win_probability=win_prob,
            current_price=price,
            ai_estimated_prob=win_prob,
        )

        if position.amount < self.position_sizer.min_position:
            return None

        return TradeSignal(
            market_id=market.id,
            token_id_yes=market.token_id_yes,
            token_id_no=market.token_id_no,
            market_question=market.question,
            end_date=market.end_date,
            action=action,
            price=price,
            size=position.amount,
            edge=edge,
            ai_confidence=analysis.confidence_score,
            reasoning=analysis.reasoning,
            timestamp=datetime.now(),
            auto_execute=auto_execute,
        )

    # ------------------------------------------------------------------
    # Helpers
    # ------------------------------------------------------------------

    @staticmethod
    def _days_to_expiry(market: Market) -> float:
        """Return calendar days until market resolution (min 0)."""
        if not market.end_date:
            return 30.0  # conservative default
        now = datetime.now(timezone.utc)
        end = market.end_date
        if end.tzinfo is None:
            end = end.replace(tzinfo=timezone.utc)
        return max(0.0, (end - now).total_seconds() / 86_400)

    def _cache_analysis(self, market_id: str, analysis: AIAnalysis) -> None:
        self.last_analysis[market_id] = analysis
        if len(self.last_analysis) > self._max_analysis_cache:
            oldest = list(self.last_analysis.keys())[
                : len(self.last_analysis) - self._max_analysis_cache
            ]
            for k in oldest:
                del self.last_analysis[k]

    def check_arbitrage_opportunity(
        self, yes_price: float, no_price: float, stake: float = 100
    ) -> Optional[float]:
        """Check for spread arbitrage. Returns profit or None."""
        return calculate_arbitrage_profit(yes_price, no_price, stake)

    def reset_processed(self):
        """Reset processed markets to allow re-analysis."""
        self.processed_markets.clear()
        logger.debug("Reset processed markets counter")
