"""Repo-visible recommendation ledger for editor review.

Runtime recommendation systems should write here instead of posting strategy
advice to Discord/Telegram. The Markdown file is intentionally human-facing so
Codex, Claude, Cursor, and the operator have one obvious place to inspect.
"""
from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Mapping, Sequence

ROOT = Path(__file__).resolve().parent.parent.parent
DEFAULT_PATH = ROOT / "docs" / "ACTIVE_RECOMMENDATIONS.md"

_HEADER = """# PSB Active Recommendations

**Purpose:** durable review queue for [[PSB]] strategy and ops recommendations generated by the bot.

**Policy:** recommendation, diagnosis, drift, and opportunity-style messages are written here for editor review. Discord remains reserved for allowed execution exits plus optional error/status notifications.

## Open Queue

"""


def _detail_lines(details: Mapping[str, Any] | None) -> list[str]:
    if not details:
        return []
    lines = []
    for key, value in details.items():
        lines.append(f"- **{key}:** `{value}`")
    return lines


def append_active_recommendation(
    *,
    source: str,
    title: str,
    body: str,
    details: Mapping[str, Any] | None = None,
    links: Sequence[str] | None = None,
    path: Path | str = DEFAULT_PATH,
) -> Path:
    """Prepend a recommendation entry to the editor-visible Markdown queue."""

    out_path = Path(path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    existing = out_path.read_text(encoding="utf-8") if out_path.exists() else _HEADER
    if "## Open Queue" not in existing:
        existing = _HEADER + "\n" + existing

    ts = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    lines = [
        f"### {ts} - {title}",
        "",
        f"- **Source:** `{source}`",
        "- **Status:** `pending_review`",
        "",
        body.strip(),
        "",
    ]
    lines.extend(_detail_lines(details))
    if links:
        lines.append("- **Links:** " + ", ".join(links))
    lines.append("")

    marker = "## Open Queue\n\n"
    if marker in existing:
        updated = existing.replace(marker, marker + "\n".join(lines), 1)
    else:
        updated = existing.rstrip() + "\n\n" + "\n".join(lines)
    out_path.write_text(updated, encoding="utf-8")
    return out_path
